moveit_setup_assistant_config:
  URDF:
    package: moveit_resources_panda_moveit_config
    relative_path: config/panda.urdf.xacro
  SRDF:
    relative_path: config/panda.srdf
  CONFIG:
    author_name: grtsinry43
    author_email: grtsinry43@outlook.com
    generated_timestamp: 1717334400
